### PR TITLE
Add missing sourcemaps

### LINKED ISSUE #7: Map file lookup fails
The output `.js` files have references to `.js.map` files that are not being checked into the repo. This is throwing warnings when trying to consume the module.

### PR DESCRIPTION
**Pull request by ruipenso**
This PR fixes the missing map files lookup.

As far I understood, the `in-memory-web-api` folder works just as a temporary folder so there's no problem of declaring the `sourceRoot` - since the files that the developer will be using are the ones at the root folder.

Fixes #7.

BTW, the project would definitely benefit with a refactor to the build process (and some documentation 😄).

### CODE REVIEW

**Comment by ruipenso** [comment]
I signed it!

**Comment by kntmrkm** [comment]
I'm waiting for this.
When merge?

**Comment by petebacondarwin** [comment]
@filipesilva any chance we could get this in?

**Comment by wardbell** [comment]
Thanks for these changes!

**Comment by ruipenso** [comment]
You're welcome. Thanks for the merge.

**Pull request closed without merging**
